export const SEARCH_OUTLET_BY_ID = 'SEARCH_OUTLET_BY_ID';
export const FETCH_OUTLET_BY_ID = 'FETCH_OUTLET_BY_ID';
export const FETCH_ALL_OUTLETS = 'FETCH_ALL_OUTLETS';
export const FETCH_BOTH_TIMES = 'FETCH_BOTH_TIMES';
export const SEARCH_ID_FOR_BOTH_TIMES = 'SEARCH_ID_FOR_BOTH_TIMES'; 